using System.Collections.Concurrent;
using System.Collections.Immutable;
using SolidWorksMcp.Protocol;

namespace SolidWorksMcp.Core;

/// <summary>Recovery outcomes deliberately distinguish a verified restore from an uncertain CAD state.</summary>
/// <remarks>
/// A recovery status is not a cosmetic log label: the transaction engine may only return the original operation
/// error after <see cref="CadRecoveryResult.PreStateVerified"/> is true.  恢复状态不是普通日志标签：只有
/// <see cref="CadRecoveryResult.PreStateVerified"/> 为 true，事务引擎才可以把原始业务错误返回给调用方；
/// 否则必须把状态标记为 rollback failed，避免把不确定状态误报成“已回滚”。
/// </remarks>
public enum CadRecoveryStatus
{
    /// <summary>No recovery was attempted because the operation did not cross a checkpoint boundary.</summary>
    NotRequired,

    /// <summary>A provider performed and verified a logical reversal.</summary>
    LogicalReversalVerified,

    /// <summary>A checkpoint copy was restored, but the provider must still prove the CAD pre-state.</summary>
    CheckpointRestored,

    /// <summary>The state could not be proven restored.</summary>
    Unrecovered,
}

/// <summary>Durable, auditable description of the pre-mutation checkpoint.</summary>
/// <remarks>
/// This is metadata, not a copy of SOLIDWORKS help or COM state.  A native provider may add a snapshot artifact, but
/// it must also use its own inspection path to prove the opaque CAD state hash after restore.  这是 metadata，不是
/// SOLIDWORKS 帮助全文或 COM 状态副本；原生 Provider 可以附加 snapshot，但恢复后仍须用 inspection 证明 CAD
/// state hash，而不能把文件存在误认为模型已恢复。
/// </remarks>
public sealed record CadCheckpointManifest
{
    /// <summary>Manifest schema version independent from the common operation envelope.</summary>
    public string SchemaVersion { get; init; } = "1.0";

    /// <summary>Unique checkpoint identity generated by the checkpoint coordinator.</summary>
    public required string CheckpointId { get; init; }

    /// <summary>Transaction identity that owns this checkpoint.</summary>
    public required TransactionId TransactionId { get; init; }

    /// <summary>Idempotency identity used to correlate retry/recovery evidence.</summary>
    public required IdempotencyKey IdempotencyKey { get; init; }

    /// <summary>Bound provider session identity.</summary>
    public required SessionId SessionId { get; init; }

    /// <summary>Bound document identity when the operation is document-scoped.</summary>
    public DocumentId? DocumentId { get; init; }

    /// <summary>Canonical source document path, if the provider has a persisted source.</summary>
    public string? SourceDocumentPath { get; init; }

    /// <summary>Opaque provider state hash captured before the first mutation.</summary>
    public string? SourceStateHash { get; init; }

    /// <summary>Hash of the copied source artifact, when a file snapshot exists.</summary>
    public string? SourceFileHash { get; init; }

    /// <summary>Provider revision recorded without exposing COM types to Core.</summary>
    public string ProviderVersion { get; init; } = "unknown";

    /// <summary>MCP/runtime contract version used to create the checkpoint.</summary>
    public string McpVersion { get; init; } = ProtocolSchema.CurrentVersion;

    /// <summary>Allowlisted operation codes whose intended effects are recorded for audit.</summary>
    public ImmutableArray<string> IntendedOperationCodes { get; init; } = [];

    /// <summary>UTC creation time for retention and incident reconstruction.</summary>
    public DateTimeOffset CreatedAtUtc { get; init; }

    /// <summary>UTC time before which this checkpoint must not be pruned.</summary>
    public DateTimeOffset RetainUntilUtc { get; init; }

    /// <summary>Absolute manifest path owned by the checkpoint store.</summary>
    public required string ManifestPath { get; init; }

    /// <summary>Absolute copied snapshot path, or null for provider-managed snapshots.</summary>
    public string? SnapshotPath { get; init; }
}

/// <summary>Checkpoint request constructed from a validated transaction plan.</summary>
public sealed record CadCheckpointRequest
{
    /// <summary>Transaction identity to include in the manifest.</summary>
    public required TransactionId TransactionId { get; init; }

    /// <summary>Idempotency identity to include in the manifest.</summary>
    public required IdempotencyKey IdempotencyKey { get; init; }

    /// <summary>Session identity to bind to the checkpoint.</summary>
    public required SessionId SessionId { get; init; }

    /// <summary>Document identity to bind to the checkpoint.</summary>
    public DocumentId? DocumentId { get; init; }

    /// <summary>Persisted source path that may be copied by a provider-aware store.</summary>
    public string? SourceDocumentPath { get; init; }

    /// <summary>Expected CAD state hash captured during preflight.</summary>
    public string? SourceStateHash { get; init; }

    /// <summary>Provider revision or installation identity for later diagnosis.</summary>
    public string ProviderVersion { get; init; } = "unknown";

    /// <summary>Operation codes and intended effects recorded in order.</summary>
    public ImmutableArray<string> IntendedOperationCodes { get; init; } = [];

    /// <summary>Retention deadline supplied by policy.</summary>
    public DateTimeOffset RetainUntilUtc { get; init; }

    /// <summary>Builds the request without copying mutable plan state into a long-lived manifest.</summary>
    public static CadCheckpointRequest FromPlan(
        CadTransactionPlan plan,
        string providerVersion,
        DateTimeOffset retainUntilUtc)
    {
        ArgumentNullException.ThrowIfNull(plan);
        ArgumentException.ThrowIfNullOrWhiteSpace(providerVersion);

        return new CadCheckpointRequest
        {
            TransactionId = plan.TransactionId,
            IdempotencyKey = plan.IdempotencyKey,
            SessionId = plan.Target.SessionId,
            DocumentId = plan.Target.DocumentId,
            SourceDocumentPath = plan.Target.DocumentPath,
            SourceStateHash = plan.Target.ExpectedStateHash,
            ProviderVersion = providerVersion.Trim(),
            IntendedOperationCodes = [.. plan.Operations.Select(operation => operation.OperationCode)],
            RetainUntilUtc = retainUntilUtc,
        };
    }
}

/// <summary>Opaque checkpoint handle returned after durable creation.</summary>
public sealed record CadCheckpoint
{
    /// <summary>Immutable checkpoint manifest.</summary>
    public required CadCheckpointManifest Manifest { get; init; }
}

/// <summary>Provider proof for one logical rollback attempt.</summary>
public sealed record CadLogicalRollbackAttempt
{
    /// <summary>Whether the provider actually applied a logical reversal.</summary>
    public required bool Applied { get; init; }

    /// <summary>Whether the provider proved the original pre-state after reversal.</summary>
    public required bool PreStateVerified { get; init; }

    /// <summary>Opaque state hash observed after the reversal.</summary>
    public string? RestoredStateHash { get; init; }
}

/// <summary>Provider/file-store proof returned by recovery.</summary>
public sealed record CadRecoveryResult
{
    /// <summary>Terminal recovery classification.</summary>
    public required CadRecoveryStatus Status { get; init; }

    /// <summary>True only when the checkpoint coordinator proved the CAD pre-state.</summary>
    public required bool PreStateVerified { get; init; }

    /// <summary>Opaque state hash observed after recovery, when available.</summary>
    public string? RestoredStateHash { get; init; }

    /// <summary>Verification scope, for example provider-state or file-bytes.</summary>
    public required string VerificationScope { get; init; }

    /// <summary>Recovery observations retained in the operation evidence bundle.</summary>
    public ImmutableArray<EvidenceObservation> Observations { get; init; } = [];
}

/// <summary>Checkpoint/recovery boundary injected into the transaction engine.</summary>
/// <remarks>
/// The engine knows when a checkpoint is mandatory, but it does not know how SOLIDWORKS saves or restores a model.
/// That ownership stays in a provider adapter.  引擎只负责判断何时必须 checkpoint，不负责猜测 SOLIDWORKS 如何保存
/// 或恢复模型；具体动作由 Provider adapter 注入，避免 COM 逻辑渗入 Core。
/// </remarks>
public interface ICadCheckpointCoordinator
{
    /// <summary>Creates the manifest and any provider-owned snapshot before mutation.</summary>
    Task<OperationResult<CadCheckpoint>> CreateAsync(
        CadCheckpointRequest request,
        CancellationToken cancellationToken = default);

    /// <summary>Attempts logical reversal first, then verified snapshot restoration.</summary>
    Task<OperationResult<CadRecoveryResult>> RecoverAsync(
        CadCheckpoint checkpoint,
        CadTransactionContext context,
        CancellationToken cancellationToken = default);
}

/// <summary>Central policy predicate for the F02 checkpoint boundary.</summary>
public static class CadCheckpointPolicy
{
    /// <summary>Default retention for a checkpoint evidence bundle.</summary>
    public static readonly TimeSpan DefaultRetention = TimeSpan.FromDays(7);

    /// <summary>Maximum time allowed for a recovery attempt before it is declared unrecovered.</summary>
    public static readonly TimeSpan RecoveryTimeout = TimeSpan.FromSeconds(30);

    /// <summary>Returns true for model, assembly, drawing, release and destructive-save mutations.</summary>
    public static bool RequiresCheckpoint(CadTransactionPlan plan)
    {
        ArgumentNullException.ThrowIfNull(plan);
        return plan.Operations.Any(operation => operation.RiskLevel >= CadRiskLevel.ModelMutation);
    }
}

/// <summary>Explicit fail-closed default used when production composition forgot to register a coordinator.</summary>
public sealed class FailClosedCadCheckpointCoordinator : ICadCheckpointCoordinator
{
    /// <inheritdoc />
    public Task<OperationResult<CadCheckpoint>> CreateAsync(
        CadCheckpointRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Task.FromResult(
            OperationResults.Failure<CadCheckpoint>(
                $"checkpoint:{request.TransactionId.Value}",
                new OperationError(
                    ErrorCodes.CheckpointFailed,
                    "No checkpoint coordinator is registered for this high-risk CAD mutation.",
                    ErrorCategories.Policy,
                    remediation: "Register a provider-aware checkpoint coordinator before enabling mutation.")));
    }

    /// <inheritdoc />
    public Task<OperationResult<CadRecoveryResult>> RecoverAsync(
        CadCheckpoint checkpoint,
        CadTransactionContext context,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(checkpoint);
        ArgumentNullException.ThrowIfNull(context);
        return Task.FromResult(
            OperationResults.Failure<CadRecoveryResult>(
                $"rollback:{context.Plan.TransactionId.Value}",
                new OperationError(
                    ErrorCodes.RollbackFailed,
                    "No recovery coordinator is registered for this checkpoint.",
                    ErrorCategories.Policy)));
    }
}

/// <summary>
/// Deterministic in-memory coordinator used only by Core tests and provider contract doubles.
/// 这是 Core 测试和 Provider contract double 专用的内存协调器，不提供生产级持久化保证。
/// </summary>
public sealed class InMemoryCadCheckpointCoordinator : ICadCheckpointCoordinator
{
    private readonly ConcurrentDictionary<string, CadCheckpoint> checkpoints = new(StringComparer.Ordinal);

    /// <summary>Creates a manifest-only checkpoint with a deterministic in-memory handle.</summary>
    public Task<OperationResult<CadCheckpoint>> CreateAsync(
        CadCheckpointRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        string checkpointId = $"memory-{Guid.NewGuid():N}";
        DateTimeOffset now = DateTimeOffset.UtcNow;
        var manifest = new CadCheckpointManifest
        {
            CheckpointId = checkpointId,
            TransactionId = request.TransactionId,
            IdempotencyKey = request.IdempotencyKey,
            SessionId = request.SessionId,
            DocumentId = request.DocumentId,
            SourceDocumentPath = request.SourceDocumentPath,
            SourceStateHash = request.SourceStateHash,
            ProviderVersion = request.ProviderVersion,
            IntendedOperationCodes = request.IntendedOperationCodes,
            CreatedAtUtc = now,
            RetainUntilUtc = request.RetainUntilUtc == default ? now.AddHours(1) : request.RetainUntilUtc,
            ManifestPath = $"memory://{checkpointId}/manifest.json",
        };
        var checkpoint = new CadCheckpoint { Manifest = manifest };
        checkpoints[checkpointId] = checkpoint;
        return Task.FromResult(
            OperationResults.Success(
                checkpoint,
                $"checkpoint:{request.TransactionId.Value}",
                new OperationEvidence(
                    "in-memory-checkpoint",
                    [
                        new EvidenceObservation("checkpoint.status", "created"),
                        new EvidenceObservation("checkpoint.id", checkpointId),
                        new EvidenceObservation("checkpoint.snapshot", "manifest-only-test-double"),
                    ])));
    }

    /// <summary>Returns a verified pre-state proof for deterministic engine tests.</summary>
    public Task<OperationResult<CadRecoveryResult>> RecoverAsync(
        CadCheckpoint checkpoint,
        CadTransactionContext context,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(checkpoint);
        ArgumentNullException.ThrowIfNull(context);
        bool known = checkpoints.ContainsKey(checkpoint.Manifest.CheckpointId);
        CadRecoveryResult recovery = new()
        {
            Status = known ? CadRecoveryStatus.CheckpointRestored : CadRecoveryStatus.Unrecovered,
            PreStateVerified = known,
            RestoredStateHash = known ? checkpoint.Manifest.SourceStateHash : null,
            VerificationScope = "deterministic-test-double",
            Observations =
            [
                new EvidenceObservation("recovery.status", known ? "checkpoint_restored" : "unrecovered"),
                new EvidenceObservation("recovery.pre_state_verified", known.ToString()),
            ],
        };
        return Task.FromResult(
            known
                ? OperationResults.Success(recovery, $"rollback:{context.Plan.TransactionId.Value}", new OperationEvidence("in-memory-checkpoint", recovery.Observations))
                : OperationResults.Failure<CadRecoveryResult>(
                    $"rollback:{context.Plan.TransactionId.Value}",
                    new OperationError(ErrorCodes.RollbackFailed, "The in-memory checkpoint handle is unknown.", ErrorCategories.Invariant),
                    new OperationEvidence("in-memory-checkpoint", recovery.Observations)));
    }
}
