#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = path.join(root, "src/tool-spec/catalog.ts");
const manifestPath = path.join(root, "tools/manifest.json");
const workerCommandPath = path.join(root, "src/generated/worker-command.ts");
const policyPath = path.join(root, "tools/generated/command-safety-policy.json");
const csharpCatalogPath = path.join(
  root,
  "workers/SolidWorksComWorker/Generated/CommandCatalog.g.cs",
);
const checkOnly = process.argv.includes("--check");

if (!fs.existsSync(catalogPath)) {
  throw new Error(`Missing ToolSpec catalog: ${catalogPath}`);
}

const catalogModule = await import(pathToFileURL(catalogPath).href);
const { TOOL_SPECS: toolSpecs } = catalogModule;

function safetyProjection(safety) {
  return {
    readOnly: safety.kind === "read",
    destructive: safety.kind === "read" ? false : safety.destructive,
    confirmRequired: safety.kind !== "read" && safety.destructive,
    autoCheckpoint: safety.kind === "modelMutation",
  };
}

function manifestFromCatalog() {
  return {
    version: "1",
    tools: toolSpecs
      .filter((spec) => spec.exposure.kind === "mcp")
      .sort((left, right) => left.implementation.command.localeCompare(right.implementation.command))
      .map((spec) => {
        const exposure = spec.exposure;
        const safety = safetyProjection(spec.safety);
        return {
          name: exposure.name,
          workerCommand: spec.implementation.command,
          tier: exposure.tier,
          ...safety,
          description: exposure.description,
          ...(exposure.descriptionSource ? { descriptionSource: exposure.descriptionSource } : {}),
          tags: [...exposure.tags],
          domains: [...exposure.domains],
          schema: exposure.input.key,
        };
      }),
  };
}

function workerCommandFromCatalog() {
  const commands = [...new Set(toolSpecs.map((spec) => spec.implementation.command))].sort();
  return [
    "// Generated by npm run generate:tools. Do not edit.",
    "",
    `export const WORKER_COMMANDS = ${JSON.stringify(commands, null, 2)} as const;`,
    "",
    "export type WorkerCommand = typeof WORKER_COMMANDS[number];",
    "",
  ].join("\n");
}

function policyFromCatalog() {
  return {
    version: "1",
    source: "src/tool-spec/catalog.ts",
    commands: toolSpecs.map((spec) => {
      const selection =
        spec.selection.kind === "bindings"
          ? {
              kind: "bindings",
              when: spec.selection.when,
              bindings: spec.selection.bindings.map((binding) => ({ ...binding })),
            }
          : { kind: spec.selection.kind };
      return {
        command: spec.implementation.command,
        csharpHandler: spec.implementation.csharpHandler,
        safety: { ...spec.safety },
        selection,
        exposure: spec.exposure.kind,
      };
    }),
  };
}

const selectionSourceNames = {
  selectedComponentName: "SelectedComponentName",
  selectedComponentPath: "SelectedComponentPath",
  selectedFeatureName: "SelectedFeatureName",
  selectedPlaneName: "SelectedPlaneName",
  selectedBodyName: "SelectedBodyName",
  selectedPersistReference: "SelectedPersistReference",
  selectedRefName: "SelectedRefName",
};

function csharpSelectionKind(selection) {
  if (selection.kind === "none") return "None";
  if (selection.kind === "context") return "Context";
  if (selection.kind === "bindings") return "Bindings";
  throw new Error(`Unsupported selection policy: ${selection.kind}`);
}

function csharpSelectionBindings(selection) {
  if (selection.kind !== "bindings") {
    return "Array.Empty<GeneratedSelectionBinding>()";
  }

  const bindings = selection.bindings.map((binding) => {
    const source = selectionSourceNames[binding.source];
    if (!source) {
      throw new Error(`Unsupported selection source: ${binding.source}`);
    }
    return `new GeneratedSelectionBinding(${JSON.stringify(binding.targetArg)}, SelectionSource.${source}, ${binding.selectionIndex ?? 1})`;
  });
  return `[${bindings.join(", ")}]`;
}

function csharpCatalogFromCatalog() {
  const selectionAwareCommands = toolSpecs
    .filter((spec) => spec.selection.kind !== "none")
    .map((spec) => spec.implementation.command)
    .sort();
  const policies = toolSpecs.map((spec) => {
    const safety = safetyProjection(spec.safety);
    return `            [${JSON.stringify(spec.implementation.command)}] = new CommandPolicy(${safety.destructive}, ${safety.autoCheckpoint}, SelectionPolicyKind.${csharpSelectionKind(spec.selection)}, ${csharpSelectionBindings(spec.selection)}),`;
  });

  return [
    "// Generated by npm run generate:tools. Do not edit.",
    "",
    "using System;",
    "using System.Collections.Generic;",
    "",
    "internal enum SelectionPolicyKind",
    "{",
    "    None,",
    "    Context,",
    "    Bindings,",
    "}",
    "",
    "internal enum SelectionSource",
    "{",
    "    SelectedComponentName,",
    "    SelectedComponentPath,",
    "    SelectedFeatureName,",
    "    SelectedPlaneName,",
    "    SelectedBodyName,",
    "    SelectedPersistReference,",
    "    SelectedRefName,",
    "}",
    "",
    "internal sealed record GeneratedSelectionBinding(",
    "    string TargetArg,",
    "    SelectionSource Source,",
    "    int SelectionIndex);",
    "",
    "internal sealed record CommandPolicy(",
    "    bool Destructive,",
    "    bool AutoCheckpoint,",
    "    SelectionPolicyKind SelectionPolicy,",
    "    IReadOnlyList<GeneratedSelectionBinding> SelectionBindings);",
    "",
    "internal static class CommandPolicyCatalog",
    "{",
    "    private static readonly IReadOnlyDictionary<string, CommandPolicy> Policies =",
    "        new Dictionary<string, CommandPolicy>(StringComparer.Ordinal)",
    "        {",
    ...policies,
    "        };",
    "",
    `    internal static readonly IReadOnlyList<string> SelectionAwareCommands = [${selectionAwareCommands.map(JSON.stringify).join(", ")}];`,
    "",
    "    internal static bool TryGet(string command, out CommandPolicy policy) =>",
    "        Policies.TryGetValue(command, out policy!);",
    "",
    "    internal static bool IsSelectionContext(string command) =>",
    "        TryGet(command, out CommandPolicy policy)",
    "        && policy.SelectionPolicy == SelectionPolicyKind.Context;",
    "",
    "    internal static bool TryGetBindings(",
    "        string command,",
    "        out IReadOnlyList<GeneratedSelectionBinding> bindings)",
    "    {",
    "        if (TryGet(command, out CommandPolicy policy)",
    "            && policy.SelectionPolicy == SelectionPolicyKind.Bindings)",
    "        {",
    "            bindings = policy.SelectionBindings;",
    "            return true;",
    "        }",
    "",
    "        bindings = Array.Empty<GeneratedSelectionBinding>();",
    "        return false;",
    "    }",
    "}",
    "",
  ].join("\n");
}

function schemaKeys(schema) {
  const definition = schema?._def;
  const shape = typeof definition?.shape === "function" ? definition.shape() : definition?.shape;
  return shape && typeof shape === "object" ? new Set(Object.keys(shape)) : null;
}

function validateToolSpecs(specs) {
  const errors = [];
  const seenCommands = new Set();
  const seenNames = new Set();
  const schemaValues = new Map();

  for (const spec of specs) {
    const implementation = spec.implementation;
    const command = implementation.command;
    if (seenCommands.has(command)) {
      errors.push(`duplicate catalog command: ${command}`);
    }
    seenCommands.add(command);

    if (implementation.kind !== "worker" || !implementation.csharpHandler) {
      errors.push(`worker command is missing a C# handler: ${command}`);
    }

    if (spec.safety.kind === "modelMutation" && spec.safety.checkpoint !== "auto") {
      errors.push(`model mutation without automatic checkpoint: ${command}`);
    }
    if (spec.safety.kind === "nonModelSideEffect") {
      if (spec.safety.checkpoint !== "notApplicable") {
        errors.push(`side effect with an applicable checkpoint: ${command}`);
      }
      if (!spec.safety.rationale.trim()) {
        errors.push(`nonModelSideEffect requires a rationale: ${command}`);
      }
    }

    if (spec.exposure.kind !== "mcp") {
      if (spec.selection.kind === "bindings") {
        errors.push(`worker-only command cannot define MCP selection bindings: ${command}`);
      }
      continue;
    }

    if (seenNames.has(spec.exposure.name)) {
      errors.push(`duplicate MCP tool name: ${spec.exposure.name}`);
    }
    seenNames.add(spec.exposure.name);

    if (!spec.exposure.description.trim()) {
      errors.push(`MCP tool has an empty description: ${command}`);
    }

    const schema = spec.exposure.input;
    if (!schema?.key || !schema?.value) {
      errors.push(`MCP tool has no schemaRef: ${command}`);
      continue;
    }

    const previous = schemaValues.get(schema.key);
    if (previous && previous !== schema.value) {
      errors.push(`schema key is paired with multiple Zod objects: ${schema.key}`);
    }
    schemaValues.set(schema.key, schema.value);

    const keys = schemaKeys(schema.value);
    if (keys && spec.selection.kind === "bindings") {
      for (const binding of spec.selection.bindings) {
        if (!keys.has(binding.targetArg)) {
          errors.push(
            `selection target ${binding.targetArg} is absent from ${schema.key}: ${command}`,
          );
        }
      }
    }
  }

  const confirmAndSave = specs.find(
    (spec) => spec.implementation.command === "confirm_and_save",
  );
  if (
    !confirmAndSave
    || confirmAndSave.safety.kind !== "modelMutation"
    || !confirmAndSave.safety.destructive
  ) {
    errors.push("confirm_and_save must be a destructive modelMutation");
  }

  return errors;
}

function expectedArtifacts() {
  return {
    manifest: `${JSON.stringify(manifestFromCatalog(), null, 2)}\n`,
    workerCommand: workerCommandFromCatalog(),
    policy: `${JSON.stringify(policyFromCatalog(), null, 2)}\n`,
    csharpCatalog: csharpCatalogFromCatalog(),
  };
}

function writeOrCheck(filePath, expected) {
  const actual = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
  if (checkOnly) {
    if (actual !== expected) {
      throw new Error(`Generated artifact drift detected: ${path.relative(root, filePath)}`);
    }
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, expected);
}

async function main() {
  const diagnostics = validateToolSpecs(toolSpecs);
  if (diagnostics.length) {
    throw new Error(`ToolSpec validation failed:\n- ${diagnostics.join("\n- ")}`);
  }

  const artifacts = expectedArtifacts();
  writeOrCheck(manifestPath, artifacts.manifest);
  writeOrCheck(workerCommandPath, artifacts.workerCommand);
  writeOrCheck(policyPath, artifacts.policy);
  writeOrCheck(csharpCatalogPath, artifacts.csharpCatalog);

  console.log(
    `${checkOnly ? "ToolSpec artifacts are current" : "Generated ToolSpec artifacts"} (${toolSpecs.length} commands)`,
  );
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (invokedPath === path.resolve(fileURLToPath(import.meta.url))) {
  await main();
}

export {
  catalogModule,
  manifestFromCatalog,
  policyFromCatalog,
  safetyProjection,
  toolSpecs,
  validateToolSpecs,
  workerCommandFromCatalog,
};
