import fs from "node:fs";
import path from "node:path";

import { z } from "zod";

import { cadUrdfPackageSchema } from "../schemas/urdf.js";

type CadUrdfPackage = z.infer<typeof cadUrdfPackageSchema>;

function esc(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;");
}

function fmt(n: number): string {
  if (!Number.isFinite(n)) {
    throw new Error(`Non-finite number in URDF output: ${n}`);
  }
  return Number(n.toPrecision(12)).toString();
}

function xyzAttr(v: readonly [number, number, number]): string {
  return `${fmt(v[0])} ${fmt(v[1])} ${fmt(v[2])}`;
}

function assertTree(pkg: CadUrdfPackage): void {
  const linkNames = new Set(pkg.links.map((link) => link.linkName));
  if (linkNames.size !== pkg.links.length) {
    throw new Error("Duplicate link names in package");
  }
  const childCounts = new Map<string, number>();
  for (const joint of pkg.joints) {
    if (!linkNames.has(joint.parent)) {
      throw new Error(`Joint ${joint.jointName} parent missing: ${joint.parent}`);
    }
    if (!linkNames.has(joint.child)) {
      throw new Error(`Joint ${joint.jointName} child missing: ${joint.child}`);
    }
    childCounts.set(joint.child, (childCounts.get(joint.child) ?? 0) + 1);
  }
  for (const [child, count] of childCounts) {
    if (count > 1) {
      throw new Error(`Link ${child} has multiple parents`);
    }
  }
  const roots = pkg.links.filter((link) => !childCounts.has(link.linkName));
  if (roots.length !== 1) {
    throw new Error(`Expected exactly one root link, found ${roots.length}`);
  }
}

export function generateUrdfXml(
  pkg: CadUrdfPackage,
  options?: { meshUriPrefix?: string; packageDir?: string },
): string {
  assertTree(pkg);
  const prefix = options?.meshUriPrefix ?? "";
  const lines: string[] = [];
  lines.push('<?xml version="1.0"?>');
  lines.push(`<!-- Generated by solidworks-mcp from CadUrdfPackage schemaVersion=${pkg.schemaVersion} -->`);
  lines.push(`<robot name="${esc(pkg.robotName)}">`);

  for (const link of pkg.links) {
    const visualUri = `${prefix}${link.visualMesh}`.replaceAll("\\", "/");
    const collisionUri = `${prefix}${link.collisionMesh}`.replaceAll("\\", "/");
    const meshOrigin = link.meshOrigin ?? { xyz: [0, 0, 0] as const, rpy: [0, 0, 0] as const };
    if (options?.packageDir) {
      const visualAbs = path.join(options.packageDir, link.visualMesh);
      const collisionAbs = path.join(options.packageDir, link.collisionMesh);
      if (!fs.existsSync(visualAbs)) {
        throw new Error(`Missing visual mesh: ${visualAbs}`);
      }
      if (!fs.existsSync(collisionAbs)) {
        throw new Error(`Missing collision mesh: ${collisionAbs}`);
      }
    }

    lines.push(`  <link name="${esc(link.linkName)}">`);
    lines.push("    <inertial>");
    lines.push(
      `      <origin xyz="${xyzAttr(link.comInLink)}" rpy="0 0 0"/>`,
    );
    lines.push(`      <mass value="${fmt(link.massKg)}"/>`);
    lines.push(
      `      <inertia ixx="${fmt(link.inertiaAboutLink.ixx)}" ixy="${fmt(link.inertiaAboutLink.ixy)}" ixz="${fmt(link.inertiaAboutLink.ixz)}" iyy="${fmt(link.inertiaAboutLink.iyy)}" iyz="${fmt(link.inertiaAboutLink.iyz)}" izz="${fmt(link.inertiaAboutLink.izz)}"/>`,
    );
    lines.push("    </inertial>");
    lines.push("    <visual>");
    lines.push(
      `      <origin xyz="${xyzAttr(meshOrigin.xyz)}" rpy="${xyzAttr(meshOrigin.rpy)}"/>`,
    );
    lines.push("      <geometry>");
    lines.push(`        <mesh filename="${esc(visualUri)}"/>`);
    lines.push("      </geometry>");
    lines.push("    </visual>");
    lines.push("    <collision>");
    lines.push(
      `      <origin xyz="${xyzAttr(meshOrigin.xyz)}" rpy="${xyzAttr(meshOrigin.rpy)}"/>`,
    );
    lines.push("      <geometry>");
    lines.push(`        <mesh filename="${esc(collisionUri)}"/>`);
    lines.push("      </geometry>");
    lines.push("    </collision>");
    lines.push("  </link>");
  }

  for (const joint of pkg.joints) {
    lines.push(`  <joint name="${esc(joint.jointName)}" type="${esc(joint.type)}">`);
    lines.push(`    <parent link="${esc(joint.parent)}"/>`);
    lines.push(`    <child link="${esc(joint.child)}"/>`);
    lines.push(
      `    <origin xyz="${xyzAttr(joint.origin.xyz)}" rpy="${xyzAttr(joint.origin.rpy)}"/>`,
    );
    if (joint.type !== "fixed") {
      lines.push(`    <axis xyz="${xyzAttr(joint.axis)}"/>`);
    }
    if (joint.type === "revolute" && joint.limit) {
      lines.push(
        `    <limit lower="${fmt(joint.limit.lower)}" upper="${fmt(joint.limit.upper)}" effort="${fmt(joint.limit.effort ?? 0)}" velocity="${fmt(joint.limit.velocity ?? 0)}"/>`,
      );
    }
    lines.push("  </joint>");
  }

  lines.push("</robot>");
  lines.push("");
  return lines.join("\n");
}

export function loadCadUrdfPackage(packageJsonPath: string): CadUrdfPackage {
  const raw = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
  return cadUrdfPackageSchema.parse(raw);
}

export function writeUrdfFromPackage(options: {
  packagePath: string;
  urdfOutputPath?: string;
  meshUriPrefix?: string;
}): { urdfPath: string; jointCount: number; linkCount: number } {
  const packageJsonPath = path.join(options.packagePath, "package.json");
  const pkg = loadCadUrdfPackage(packageJsonPath);
  const urdfPath = options.urdfOutputPath
    ?? path.join(options.packagePath, `${pkg.robotName}.urdf`);
  const xml = generateUrdfXml(pkg, {
    meshUriPrefix: options.meshUriPrefix,
    packageDir: options.packagePath,
  });
  fs.mkdirSync(path.dirname(urdfPath), { recursive: true });
  fs.writeFileSync(urdfPath, xml, "utf8");
  return {
    urdfPath,
    jointCount: pkg.joints.length,
    linkCount: pkg.links.length,
  };
}
