// Authored ToolSpec metadata. Generated artifacts are projections of this catalog.
import { z } from "zod";
import type { WorkerCommand } from "../generated/worker-command.js";
import * as assemblySchemas from "../schemas/assembly.js";
import * as documentSchemas from "../schemas/document.js";
import * as mateSchemas from "../schemas/mate.js";
import * as partSchemas from "../schemas/part.js";
import * as urdfSchemas from "../schemas/urdf.js";

export type ToolTier = "core" | "extended" | "advanced" | "debug";

export interface SchemaRef<K extends string = string, T extends z.ZodTypeAny = z.ZodTypeAny> {
  readonly key: K;
  readonly value: T;
}

export function schemaRef<const K extends string, T extends z.ZodTypeAny>(
  key: K,
  value: T,
): SchemaRef<K, T> {
  return { key, value };
}

export type ToolSafety =
  | { readonly kind: "read" }
  | {
      readonly kind: "modelMutation";
      readonly destructive: boolean;
      readonly checkpoint: "auto";
    }
  | {
      readonly kind: "nonModelSideEffect";
      readonly destructive: boolean;
      readonly checkpoint: "notApplicable";
      readonly rationale: string;
    };

export const readSafety = (): ToolSafety => ({ kind: "read" });

export function modelMutation(args: { readonly destructive: boolean }): ToolSafety {
  return { kind: "modelMutation", destructive: args.destructive, checkpoint: "auto" };
}

export function nonModelSideEffect(args: { readonly destructive: boolean; readonly rationale: string }): ToolSafety {
  if (!args.rationale.trim()) {
    throw new Error("nonModelSideEffect requires a rationale");
  }
  return { kind: "nonModelSideEffect", destructive: args.destructive, checkpoint: "notApplicable", rationale: args.rationale };
}

export type SelectionSource =
  | "selectedComponentName"
  | "selectedComponentPath"
  | "selectedFeatureName"
  | "selectedPlaneName"
  | "selectedBodyName"
  | "selectedPersistReference"
  | "selectedRefName";

export interface SelectionBinding {
  readonly targetArg: string;
  readonly source: SelectionSource;
  readonly selectionIndex?: 1 | 2;
}

export type SelectionPolicy =
  | { readonly kind: "none" }
  | { readonly kind: "context" }
  | {
      readonly kind: "bindings";
      readonly when: "use_selection";
      readonly bindings: readonly SelectionBinding[];
    };

export const noSelection: SelectionPolicy = { kind: "none" };

export function bindSelection(bindings: readonly SelectionBinding[]): SelectionPolicy {
  return { kind: "bindings", when: "use_selection", bindings };
}

export const selectionContext: SelectionPolicy = { kind: "context" };

export type Implementation = {
  readonly kind: "worker";
  readonly command: WorkerCommand;
  readonly csharpHandler: `${string}.${string}`;
};

export type McpExposure = {
  readonly kind: "mcp";
  readonly name: `solidworks_${string}`;
  readonly tier: ToolTier;
  readonly description: string;
  readonly descriptionSource?: "authored" | "derived";
  readonly input: SchemaRef;
  readonly tags: readonly string[];
  readonly domains: readonly string[];
};

export type Exposure = McpExposure | { readonly kind: "workerOnly" };

export const workerOnly = (): Exposure => ({ kind: "workerOnly" });

export function worker(command: WorkerCommand, csharpHandler: `${string}.${string}`): Implementation {
  return { kind: "worker", command, csharpHandler };
}

export function mcp(exposure: Omit<McpExposure, "kind">): McpExposure {
  return { kind: "mcp", ...exposure };
}

export interface ToolSpec {
  readonly implementation: Implementation;
  readonly exposure: Exposure;
  readonly safety: ToolSafety;
  readonly selection: SelectionPolicy;
}

export function tool<const T extends ToolSpec>(spec: T): T {
  return spec;
}

export const SCHEMAS = {
  addConfigurationCopy: schemaRef("addConfigurationCopy", partSchemas.addConfigurationCopySchema),
  addStandardViews: schemaRef("addStandardViews", partSchemas.addStandardViewsSchema),
  align: schemaRef("align", assemblySchemas.alignSchema),
  checkpoint: schemaRef("checkpoint", documentSchemas.checkpointSchema),
  cloneSolidBodyPart: schemaRef("cloneSolidBodyPart", assemblySchemas.cloneSolidBodyPartSchema),
  closeAllDocuments: schemaRef("closeAllDocuments", documentSchemas.closeAllDocumentsSchema),
  closeDocument: schemaRef("closeDocument", documentSchemas.closeDocumentSchema),
  componentName: schemaRef("componentName", assemblySchemas.componentNameSchema),
  confirmAndSave: schemaRef("confirmAndSave", documentSchemas.confirmAndSaveSchema),
  copyWithMates: schemaRef("copyWithMates", assemblySchemas.copyWithMatesSchema),
  createDrawingFromModel: schemaRef("createDrawingFromModel", partSchemas.createDrawingFromModelSchema),
  createSketch: schemaRef("createSketch", partSchemas.createSketchSchema),
  createSubassembly: schemaRef("createSubassembly", partSchemas.createSubassemblySchema),
  deleteAllMates: schemaRef("deleteAllMates", assemblySchemas.deleteAllMatesSchema),
  deleteFeature: schemaRef("deleteFeature", partSchemas.deleteFeatureSchema),
  demoBuildPart: schemaRef("demoBuildPart", partSchemas.demoBuildPartSchema),
  deleteMate: schemaRef("deleteMate", assemblySchemas.deleteMateSchema),
  deleteMatesInRange: schemaRef("deleteMatesInRange", assemblySchemas.deleteMatesInRangeSchema),
  diagnose: schemaRef("diagnose", documentSchemas.diagnoseSchema),
  diagnosePartSave: schemaRef("diagnosePartSave", documentSchemas.diagnosePartSaveSchema),
  dissolveComponent: schemaRef("dissolveComponent", assemblySchemas.dissolveComponentSchema),
  ensureOffsetPlane: schemaRef("ensureOffsetPlane", partSchemas.ensureOffsetPlaneSchema),
  explainError: schemaRef("explainError", documentSchemas.explainErrorSchema),
  explodeView: schemaRef("explodeView", assemblySchemas.explodeViewSchema),
  export: schemaRef("export", documentSchemas.exportSchema),
  exportLinkTransforms: schemaRef("exportLinkTransforms", assemblySchemas.exportLinkTransformsSchema),
  exportUrdfPackage: schemaRef("exportUrdfPackage", urdfSchemas.exportUrdfPackageSchema),
  featureChamfer: schemaRef("featureChamfer", partSchemas.featureChamferSchema),
  featureCircularPattern: schemaRef("featureCircularPattern", partSchemas.featureCircularPatternSchema),
  featureExtrudeBoss: schemaRef("featureExtrudeBoss", partSchemas.featureExtrudeBossSchema),
  featureExtrudeCut: schemaRef("featureExtrudeCut", partSchemas.featureExtrudeCutSchema),
  combineBodies: schemaRef("combineBodies", partSchemas.combineBodiesSchema),
  featureFillet: schemaRef("featureFillet", partSchemas.featureFilletSchema),
  featureLinearPattern: schemaRef("featureLinearPattern", partSchemas.featureLinearPatternSchema),
  featureMirror: schemaRef("featureMirror", partSchemas.featureMirrorSchema),
  featureProbe: schemaRef("featureProbe", assemblySchemas.featureProbeSchema),
  getAssemblyDegreesOfFreedom: schemaRef("getAssemblyDegreesOfFreedom", assemblySchemas.getAssemblyDegreesOfFreedomSchema),
  getMateLimitAngle: schemaRef("getMateLimitAngle", urdfSchemas.getMateLimitAngleSchema),
  importStep: schemaRef("importStep", documentSchemas.importStepSchema),
  insertComponent: schemaRef("insertComponent", assemblySchemas.insertComponentSchema),
  listCheckpoints: schemaRef("listCheckpoints", documentSchemas.listCheckpointsSchema),
  makeComponentIndependent: schemaRef("makeComponentIndependent", assemblySchemas.makeComponentIndependentSchema),
  mateLimitAngle: schemaRef("mateLimitAngle", mateSchemas.mateLimitAngleSchema),
  mateRefs: schemaRef("mateRefs", mateSchemas.mateRefsSchema),
  mateTry: schemaRef("mateTry", mateSchemas.mateTrySchema),
  measureDistance: schemaRef("measureDistance", assemblySchemas.measureDistanceSchema),
  mirrorComponent: schemaRef("mirrorComponent", assemblySchemas.mirrorComponentSchema),
  mirrorPartFile: schemaRef("mirrorPartFile", assemblySchemas.mirrorPartFileSchema),
  newDocument: schemaRef("newDocument", partSchemas.newDocumentSchema),
  open: schemaRef("open", documentSchemas.openSchema),
  optionalPath: schemaRef("optionalPath", documentSchemas.optionalPathSchema),
  packAndGo: schemaRef("packAndGo", partSchemas.packAndGoSchema),
  partFeatureProbe: schemaRef("partFeatureProbe", assemblySchemas.partFeatureProbeSchema),
  persistRef: schemaRef("persistRef", assemblySchemas.persistRefSchema),
  probeAngleTravel: schemaRef("probeAngleTravel", mateSchemas.probeAngleTravelSchema),
  probePartFeatureGeometry: schemaRef("probePartFeatureGeometry", partSchemas.probePartFeatureGeometrySchema),
  rebuildDocument: schemaRef("rebuildDocument", documentSchemas.rebuildDocumentSchema),
  renameFeature: schemaRef("renameFeature", documentSchemas.renameFeatureSchema),
  replaceComponentPath: schemaRef("replaceComponentPath", assemblySchemas.replaceComponentPathSchema),
  replaceComponentsByPath: schemaRef("replaceComponentsByPath", assemblySchemas.replaceComponentsByPathSchema),
  resolveLightweight: schemaRef("resolveLightweight", documentSchemas.resolveLightweightSchema),
  restoreFromCheckpoint: schemaRef("restoreFromCheckpoint", documentSchemas.restoreFromCheckpointSchema),
  roundSideArmsFromCircle: schemaRef("roundSideArmsFromCircle", partSchemas.roundSideArmsFromCircleSchema),
  saveDocument: schemaRef("saveDocument", documentSchemas.saveDocumentSchema),
  selectByPersistReference: schemaRef("selectByPersistReference", assemblySchemas.selectByPersistReferenceSchema),
  setComponentConfiguration: schemaRef("setComponentConfiguration", assemblySchemas.setComponentConfigurationSchema),
  setComponentTransform: schemaRef("setComponentTransform", assemblySchemas.setComponentTransformSchema),
  setCustomProperties: schemaRef("setCustomProperties", documentSchemas.setCustomPropertiesSchema),
  setDimension: schemaRef("setDimension", assemblySchemas.setDimensionSchema),
  setFeatureSuppression: schemaRef("setFeatureSuppression", assemblySchemas.setFeatureSuppressionSchema),
  setMassOverride: schemaRef("setMassOverride", documentSchemas.setMassOverrideSchema),
  setMateLimitAngle: schemaRef("setMateLimitAngle", mateSchemas.setMateLimitAngleSchema),
  setMaterial: schemaRef("setMaterial", partSchemas.setMaterialSchema),
  setMateSuppression: schemaRef("setMateSuppression", assemblySchemas.setMateSuppressionSchema),
  setSketchCircleDiameter: schemaRef("setSketchCircleDiameter", partSchemas.setSketchCircleDiameterSchema),
  sketchCircle: schemaRef("sketchCircle", partSchemas.sketchCircleSchema),
  sketchLine: schemaRef("sketchLine", partSchemas.sketchLineSchema),
  sketchRectangle: schemaRef("sketchRectangle", partSchemas.sketchRectangleSchema),
  transformComponent: schemaRef("transformComponent", assemblySchemas.transformComponentSchema),
  unfixAllComponents: schemaRef("unfixAllComponents", documentSchemas.unfixAllComponentsSchema),
} as const;

export const TOOL_SPECS = [
  tool({
    implementation: worker("status", "Program.Status"),
    exposure: workerOnly(),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("open", "Program.Open"),
    exposure: mcp({
      name: "solidworks_open",
      tier: "core",
      description: "Open a SolidWorks or STEP document from an allowed CAD root.",
      descriptionSource: "authored",
      input: SCHEMAS["open"],
      tags: ["open"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("export", "Program.Export"),
    exposure: mcp({
      name: "solidworks_export",
      tier: "core",
      description: "Export a CAD document to STEP, STL, PDF, or PNG under an allowed CAD root.",
      descriptionSource: "authored",
      input: SCHEMAS["export"],
      tags: ["export"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("measure", "Program.Measure"),
    exposure: mcp({
      name: "solidworks_measure",
      tier: "core",
      description: "Return bounding-box and mass-property metadata for a CAD document.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["measure"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_features", "Program.ListFeatures"),
    exposure: mcp({
      name: "solidworks_list_features",
      tier: "extended",
      description: "List top-level feature tree entries for a CAD document.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("inspect_document", "Program.InspectDocument"),
    exposure: mcp({
      name: "solidworks_inspect_document",
      tier: "core",
      description: "Return document type, path, saved state, units, and custom properties.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["inspect"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_components", "Program.ListComponents"),
    exposure: mcp({
      name: "solidworks_list_components",
      tier: "core",
      description: "Return the assembly component tree with paths, quantities, and states.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_reference_geometry", "Program.ListReferenceGeometry"),
    exposure: mcp({
      name: "solidworks_list_reference_geometry",
      tier: "core",
      description: "List named reference planes, axes, coordinate systems, and points.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("urdf_readiness", "Program.UrdfReadiness"),
    exposure: workerOnly(),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_feature_errors", "Program.ListFeatureErrors"),
    exposure: workerOnly(),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_mate_limit_angle", "Program.GetMateLimitAngle"),
    exposure: mcp({
      name: "solidworks_get_mate_limit_angle",
      tier: "extended",
      description: "Read the minimum, maximum, and current angle of a named SolidWorks limit-angle mate.",
      descriptionSource: "authored",
      input: SCHEMAS["getMateLimitAngle"],
      tags: ["get", "mate", "urdf"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("export_urdf_package", "Program.ExportUrdfPackage"),
    exposure: mcp({
      name: "solidworks_export_urdf_package",
      tier: "advanced",
      description: "Export a validated CAD assembly and manifest into a versioned URDF package.",
      descriptionSource: "authored",
      input: SCHEMAS["exportUrdfPackage"],
      tags: ["export", "urdf", "package"],
      domains: ["assembly", "document"],
    }),
    safety: nonModelSideEffect({
      destructive: false,
      rationale: "The command reads CAD state and writes a separate package directory.",
    }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("add_urdf_frame", "Program.AddUrdfFrame"),
    exposure: workerOnly(),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_bom", "Program.ListBom"),
    exposure: mcp({
      name: "solidworks_list_bom",
      tier: "extended",
      description: "Return a flat component list as a bill-of-materials precursor.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_mates", "Program.ListMates"),
    exposure: mcp({
      name: "solidworks_list_mates",
      tier: "core",
      description: "Return mate feature names and types for an assembly.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_mate_entities", "Program.ListMateEntities"),
    exposure: mcp({
      name: "solidworks_list_mate_entities",
      tier: "extended",
      description: "Worker command: list_mate_entities",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_component_visible", "Program.SetComponentVisible"),
    exposure: mcp({
      name: "solidworks_set_component_visible",
      tier: "extended",
      description: "Set component visible.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("set_component_fixed", "Program.SetComponentFixed"),
    exposure: mcp({
      name: "solidworks_set_component_fixed",
      tier: "extended",
      description: "Set component fixed.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("rename_component", "Program.RenameComponent"),
    exposure: mcp({
      name: "solidworks_rename_component",
      tier: "extended",
      description: "Rename component.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["rename"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("rename_feature", "Program.RenameFeature"),
    exposure: mcp({
      name: "solidworks_rename_feature",
      tier: "extended",
      description: "Rename a FeatureManager feature, including mates and reference geometry.",
      descriptionSource: "authored",
      input: SCHEMAS["renameFeature"],
      tags: ["rename", "feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_coord_sys", "Program.MateCoordSys"),
    exposure: mcp({
      name: "solidworks_mate_coord_sys",
      tier: "extended",
      description: "Create a coord sys mate between assembly references.",
      descriptionSource: "derived",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("delete_all_mates", "Program.DeleteAllMates"),
    exposure: mcp({
      name: "solidworks_delete_all_mates",
      tier: "extended",
      description: "Delete all mates from an assembly.",
      descriptionSource: "authored",
      input: SCHEMAS["deleteAllMates"],
      tags: ["delete"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("delete_mates_in_range", "Program.DeleteMatesInRange"),
    exposure: mcp({
      name: "solidworks_delete_mates_in_range",
      tier: "extended",
      description: "Delete mates in range.",
      descriptionSource: "derived",
      input: SCHEMAS["deleteMatesInRange"],
      tags: ["delete"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("delete_mate", "Program.DeleteMate"),
    exposure: mcp({
      name: "solidworks_delete_mate",
      tier: "extended",
      description: "Delete a named mate feature from an assembly.",
      descriptionSource: "authored",
      input: SCHEMAS["deleteMate"],
      tags: ["delete"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("unfix_all_components", "Program.UnfixAllComponents"),
    exposure: mcp({
      name: "solidworks_unfix_all_components",
      tier: "extended",
      description: "Unfix all components.",
      descriptionSource: "derived",
      input: SCHEMAS["unfixAllComponents"],
      tags: ["unfix"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_component_configuration", "Program.SetComponentConfiguration"),
    exposure: mcp({
      name: "solidworks_set_component_configuration",
      tier: "extended",
      description: "Set component configuration.",
      descriptionSource: "derived",
      input: SCHEMAS["setComponentConfiguration"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_component_origin", "Program.MateComponentOrigin"),
    exposure: mcp({
      name: "solidworks_mate_component_origin",
      tier: "extended",
      description: "Create a component origin mate between assembly references.",
      descriptionSource: "derived",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_configurations", "Program.ListConfigurations"),
    exposure: mcp({
      name: "solidworks_list_configurations",
      tier: "extended",
      description: "List configuration names for a part document.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_dimensions", "Program.ListDimensions"),
    exposure: mcp({
      name: "solidworks_list_dimensions",
      tier: "extended",
      description: "List driving dimensions in a part, optionally for one configuration.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_feature_suppression", "Program.SetFeatureSuppression"),
    exposure: mcp({
      name: "solidworks_set_feature_suppression",
      tier: "extended",
      description: "Set feature suppression.",
      descriptionSource: "derived",
      input: SCHEMAS["setFeatureSuppression"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("add_configuration_copy", "Program.AddConfigurationCopy"),
    exposure: mcp({
      name: "solidworks_add_configuration_copy",
      tier: "extended",
      description: "Add configuration copy.",
      descriptionSource: "derived",
      input: SCHEMAS["addConfigurationCopy"],
      tags: ["add"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_component_box", "Program.GetComponentBox"),
    exposure: mcp({
      name: "solidworks_get_component_box",
      tier: "extended",
      description: "Get component box.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("transform_component", "Program.TransformComponent"),
    exposure: mcp({
      name: "solidworks_transform_component",
      tier: "extended",
      description: "Transform component.",
      descriptionSource: "derived",
      input: SCHEMAS["transformComponent"],
      tags: ["transform"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("set_component_transform", "Program.SetComponentTransform"),
    exposure: mcp({
      name: "solidworks_set_component_transform",
      tier: "extended",
      description: "Apply a 4x4 transform matrix to an assembly component.",
      descriptionSource: "authored",
      input: SCHEMAS["setComponentTransform"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("set_dimension", "Program.SetDimension"),
    exposure: mcp({
      name: "solidworks_set_dimension",
      tier: "extended",
      description: "Set a driving part dimension value in meters.",
      descriptionSource: "authored",
      input: SCHEMAS["setDimension"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_planes", "Program.MatePlanes"),
    exposure: mcp({
      name: "solidworks_mate_planes",
      tier: "extended",
      description: "Add a coincident or parallel mate between named planes on two components.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("get_feature_box", "Program.GetFeatureBox"),
    exposure: mcp({
      name: "solidworks_get_feature_box",
      tier: "extended",
      description: "Return the assembly-space bounding box for a named component feature.",
      descriptionSource: "authored",
      input: SCHEMAS["featureProbe"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "feature_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("mate_coincident", "Program.MateCoincident"),
    exposure: mcp({
      name: "solidworks_mate_coincident",
      tier: "core",
      description: "Add a coincident mate between two component references or selected faces.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_parallel", "Program.MateParallel"),
    exposure: mcp({
      name: "solidworks_mate_parallel",
      tier: "core",
      description: "Add a parallel mate between two component references or selected faces.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_tangent", "Program.MateTangent"),
    exposure: mcp({
      name: "solidworks_mate_tangent",
      tier: "extended",
      description: "Worker command: mate_tangent",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_try_coincident", "Program.MateTryCoincident"),
    exposure: mcp({
      name: "solidworks_mate_try_coincident",
      tier: "debug",
      description: "Dry-run a coincident mate without committing it.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_try_parallel", "Program.MateTryParallel"),
    exposure: mcp({
      name: "solidworks_mate_try_parallel",
      tier: "debug",
      description: "Dry-run a parallel mate without committing it.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_try_distance", "Program.MateTryDistance"),
    exposure: mcp({
      name: "solidworks_mate_try_distance",
      tier: "debug",
      description: "Dry-run a distance mate without committing it.",
      descriptionSource: "authored",
      input: SCHEMAS["mateTry"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_try_perpendicular", "Program.MateTryPerpendicular"),
    exposure: mcp({
      name: "solidworks_mate_try_perpendicular",
      tier: "debug",
      description: "Dry-run a perpendicular mate without committing it.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_try_width", "Program.MateTryWidth"),
    exposure: mcp({
      name: "solidworks_mate_try_width",
      tier: "debug",
      description: "Dry-run a width mate without committing it.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_distance", "Program.MateDistance"),
    exposure: mcp({
      name: "solidworks_mate_distance",
      tier: "extended",
      description: "Add a distance mate between two component references or selected faces.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_perpendicular", "Program.MatePerpendicular"),
    exposure: mcp({
      name: "solidworks_mate_perpendicular",
      tier: "extended",
      description: "Add a perpendicular mate between two component references or selected faces.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_width", "Program.MateWidth"),
    exposure: mcp({
      name: "solidworks_mate_width",
      tier: "extended",
      description: "Add a width mate between two component references or selected faces.",
      descriptionSource: "authored",
      input: SCHEMAS["mateRefs"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_1", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref_1", source: "selectedRefName", selectionIndex: 1 }, { targetArg: "component_2", source: "selectedComponentName", selectionIndex: 2 }, { targetArg: "ref_2", source: "selectedRefName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("mate_limit_angle", "Program.MateLimitAngle"),
    exposure: mcp({
      name: "solidworks_mate_limit_angle",
      tier: "core",
      description: "Add a limit-angle mate with min/max rotation about an axis.",
      descriptionSource: "authored",
      input: SCHEMAS["mateLimitAngle"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_mate_limit_angle", "Program.SetMateLimitAngle"),
    exposure: mcp({
      name: "solidworks_set_mate_limit_angle",
      tier: "extended",
      description: "Worker command: set_mate_limit_angle",
      input: SCHEMAS["setMateLimitAngle"],
      tags: ["set"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("probe_angle_travel", "Program.ProbeAngleTravel"),
    exposure: mcp({
      name: "solidworks_probe_angle_travel",
      tier: "extended",
      description: "Probe angular travel of a component about an axis within optional limits.",
      descriptionSource: "authored",
      input: SCHEMAS["probeAngleTravel"],
      tags: ["probe"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_record_macro", "Program.MateRecordMacro"),
    exposure: mcp({
      name: "solidworks_mate_record_macro",
      tier: "extended",
      description: "Create a record macro mate between assembly references.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_replay_sequence", "Program.MateReplaySequence"),
    exposure: mcp({
      name: "solidworks_mate_replay_sequence",
      tier: "extended",
      description: "Create a replay sequence mate between assembly references.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mate_probe", "Program.MateProbe"),
    exposure: mcp({
      name: "solidworks_mate_probe",
      tier: "extended",
      description: "Inspect candidate mate entities and report whether a mate is likely to succeed.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["mate"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("align_component_to_feature", "Program.AlignComponentToFeature"),
    exposure: mcp({
      name: "solidworks_align_component_to_feature",
      tier: "extended",
      description: "Align component to feature.",
      descriptionSource: "derived",
      input: SCHEMAS["align"],
      tags: ["align"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "layout_component", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "layout_feature", source: "selectedFeatureName", selectionIndex: 1 }, { targetArg: "target_component", source: "selectedComponentName", selectionIndex: 2 }]),
  }),
  tool({
    implementation: worker("probe_feature_faces", "Program.ProbeFeatureFaces"),
    exposure: mcp({
      name: "solidworks_probe_feature_faces",
      tier: "extended",
      description: "List face count, area, and planarity for a component feature.",
      descriptionSource: "authored",
      input: SCHEMAS["featureProbe"],
      tags: ["probe"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "feature_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("get_part_feature_box", "Program.GetPartFeatureBox"),
    exposure: mcp({
      name: "solidworks_get_part_feature_box",
      tier: "extended",
      description: "Get part feature box.",
      descriptionSource: "derived",
      input: SCHEMAS["partFeatureProbe"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "part_path", source: "selectedComponentPath", selectionIndex: 1 }, { targetArg: "feature_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("probe_part_feature_geometry", "Program.ProbePartFeatureGeometry"),
    exposure: mcp({
      name: "solidworks_probe_part_feature_geometry",
      tier: "extended",
      description: "Inspect a part feature's dimensions, faces, cylinders, and sketch geometry.",
      descriptionSource: "authored",
      input: SCHEMAS["probePartFeatureGeometry"],
      tags: ["probe", "geometry"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "feature_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("get_planar_face_index", "Program.GetPlanarFaceIndex"),
    exposure: mcp({
      name: "solidworks_get_planar_face_index",
      tier: "extended",
      description: "Get planar face index.",
      descriptionSource: "derived",
      input: SCHEMAS["featureProbe"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "feature_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("select_face_by_ray", "Program.SelectFaceByRay"),
    exposure: mcp({
      name: "solidworks_select_face_by_ray",
      tier: "extended",
      description: "Select face by ray.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["select"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_persist_reference", "Program.GetPersistReference"),
    exposure: mcp({
      name: "solidworks_get_persist_reference",
      tier: "extended",
      description: "Capture a base64 persist reference for a component reference.",
      descriptionSource: "authored",
      input: SCHEMAS["persistRef"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }, { targetArg: "ref", source: "selectedRefName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("select_by_persist_reference", "Program.SelectByPersistReference"),
    exposure: mcp({
      name: "solidworks_select_by_persist_reference",
      tier: "extended",
      description: "Select an entity using a base64 persist reference.",
      descriptionSource: "authored",
      input: SCHEMAS["selectByPersistReference"],
      tags: ["select"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("rebuild_document", "Program.RebuildDocument"),
    exposure: mcp({
      name: "solidworks_rebuild_document",
      tier: "core",
      description: "Rebuild the active model.",
      descriptionSource: "authored",
      input: SCHEMAS["rebuildDocument"],
      tags: ["rebuild"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("ensure_offset_plane", "Program.EnsureOffsetPlane"),
    exposure: mcp({
      name: "solidworks_ensure_offset_plane",
      tier: "extended",
      description: "Ensure offset plane.",
      descriptionSource: "derived",
      input: SCHEMAS["ensureOffsetPlane"],
      tags: ["ensure"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("reset_component_transform", "Program.ResetComponentTransform"),
    exposure: mcp({
      name: "solidworks_reset_component_transform",
      tier: "extended",
      description: "Reset component transform.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["reset"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("insert_coord_sys", "Program.InsertCoordSys"),
    exposure: mcp({
      name: "solidworks_insert_coord_sys",
      tier: "extended",
      description: "Insert coord sys.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["insert"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_interferences", "Program.ListInterferences"),
    exposure: mcp({
      name: "solidworks_list_interferences",
      tier: "extended",
      description: "Run interference detection on an assembly.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_mate_suppression", "Program.SetMateSuppression"),
    exposure: mcp({
      name: "solidworks_set_mate_suppression",
      tier: "extended",
      description: "Suppress or unsuppress a named mate.",
      descriptionSource: "authored",
      input: SCHEMAS["setMateSuppression"],
      tags: ["set"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("save_document", "Program.SaveDocument"),
    exposure: mcp({
      name: "solidworks_save_document",
      tier: "core",
      description: "Save the active or specified SolidWorks document.",
      descriptionSource: "authored",
      input: SCHEMAS["saveDocument"],
      tags: ["save"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("confirm_and_save", "Program.ConfirmAndSave"),
    exposure: mcp({
      name: "solidworks_confirm_and_save",
      tier: "core",
      description: "Worker command: confirm_and_save",
      input: SCHEMAS["confirmAndSave"],
      tags: ["confirm"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("close_all_documents", "Program.CloseAllDocuments"),
    exposure: mcp({
      name: "solidworks_close_all_documents",
      tier: "extended",
      description: "Close all documents.",
      descriptionSource: "derived",
      input: SCHEMAS["closeAllDocuments"],
      tags: ["close"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: true, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("diagnose_part_save", "Program.DiagnosePartSave"),
    exposure: mcp({
      name: "solidworks_diagnose_part_save",
      tier: "debug",
      description: "Diagnose part save.",
      descriptionSource: "derived",
      input: SCHEMAS["diagnosePartSave"],
      tags: ["diagnose"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("clone_solid_body_part", "Program.CloneSolidBodyPart"),
    exposure: mcp({
      name: "solidworks_clone_solid_body_part",
      tier: "extended",
      description: "Clone solid body part.",
      descriptionSource: "derived",
      input: SCHEMAS["cloneSolidBodyPart"],
      tags: ["clone"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mirror_part_file", "Program.MirrorPartFile"),
    exposure: mcp({
      name: "solidworks_mirror_part_file",
      tier: "extended",
      description: "Mirror part file.",
      descriptionSource: "derived",
      input: SCHEMAS["mirrorPartFile"],
      tags: ["mirror"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("make_component_independent", "Program.MakeComponentIndependent"),
    exposure: mcp({
      name: "solidworks_make_component_independent",
      tier: "extended",
      description: "Make component independent.",
      descriptionSource: "derived",
      input: SCHEMAS["makeComponentIndependent"],
      tags: ["make"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_custom_properties", "Program.SetCustomProperties"),
    exposure: mcp({
      name: "solidworks_set_custom_properties",
      tier: "core",
      description: "Set custom properties on a part or assembly and optionally save it.",
      descriptionSource: "authored",
      input: SCHEMAS["setCustomProperties"],
      tags: ["set"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("replace_components_by_path", "Program.ReplaceComponentsByPath"),
    exposure: mcp({
      name: "solidworks_replace_components_by_path",
      tier: "extended",
      description: "Replace components by path.",
      descriptionSource: "derived",
      input: SCHEMAS["replaceComponentsByPath"],
      tags: ["replace"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("replace_component_path", "Program.ReplaceComponentPath"),
    exposure: mcp({
      name: "solidworks_replace_component_path",
      tier: "extended",
      description: "Replace component path.",
      descriptionSource: "derived",
      input: SCHEMAS["replaceComponentPath"],
      tags: ["replace"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_component_transform", "Program.GetComponentTransform"),
    exposure: mcp({
      name: "solidworks_get_component_transform",
      tier: "extended",
      description: "Return the 4x4 transform matrix for a named assembly component.",
      descriptionSource: "authored",
      input: SCHEMAS["componentName"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("insert_component", "Program.InsertComponent"),
    exposure: mcp({
      name: "solidworks_insert_component",
      tier: "extended",
      description: "Insert a part into an assembly from an allowed path.",
      descriptionSource: "authored",
      input: SCHEMAS["insertComponent"],
      tags: ["insert"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("debug_mate_entities", "Program.DebugMateEntities"),
    exposure: mcp({
      name: "solidworks_debug_mate_entities",
      tier: "debug",
      description: "Debug mate entities.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["debug"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("assembly_diagnostics", "Program.AssemblyDiagnostics"),
    exposure: mcp({
      name: "solidworks_assembly_diagnostics",
      tier: "extended",
      description: "Summarize fixed, lightweight, suppressed, broken-reference, and mate state.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["assembly"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("component_mass_properties", "Program.ComponentMassProperties"),
    exposure: mcp({
      name: "solidworks_component_mass_properties",
      tier: "extended",
      description: "Return mass, center of mass, and inertia for a component.",
      descriptionSource: "authored",
      input: SCHEMAS["componentName"],
      tags: ["component"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("resolve_lightweight", "Program.ResolveLightweight"),
    exposure: mcp({
      name: "solidworks_resolve_lightweight",
      tier: "extended",
      description: "Resolve all lightweight components in an assembly.",
      descriptionSource: "authored",
      input: SCHEMAS["resolveLightweight"],
      tags: ["resolve"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("invoke", "Program.Invoke"),
    exposure: workerOnly(),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("batch_invoke", "Program.BatchInvoke"),
    exposure: workerOnly(),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("checkpoint_document", "Program.CheckpointDocument"),
    exposure: mcp({
      name: "solidworks_checkpoint_document",
      tier: "core",
      description: "Save a recoverable checkpoint of the active or specified document.",
      descriptionSource: "authored",
      input: SCHEMAS["checkpoint"],
      tags: ["checkpoint"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_checkpoints", "Program.ListCheckpoints"),
    exposure: mcp({
      name: "solidworks_list_checkpoints",
      tier: "core",
      description: "Worker command: list_checkpoints",
      input: SCHEMAS["listCheckpoints"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("restore_from_checkpoint", "Program.RestoreFromCheckpoint"),
    exposure: mcp({
      name: "solidworks_restore_from_checkpoint",
      tier: "extended",
      description: "Worker command: restore_from_checkpoint",
      input: SCHEMAS["restoreFromCheckpoint"],
      tags: ["restore"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: true, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("diagnose_com", "Program.DiagnoseCom"),
    exposure: mcp({
      name: "solidworks_diagnose_com",
      tier: "core",
      description: "Diagnose SolidWorks COM attach, ROT, and worker mutex health.",
      descriptionSource: "authored",
      input: SCHEMAS["diagnose"],
      tags: ["diagnose"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("diagnose_document", "Program.DiagnoseDocument"),
    exposure: mcp({
      name: "solidworks_diagnose_document",
      tier: "debug",
      description: "Diagnose document.",
      descriptionSource: "derived",
      input: SCHEMAS["diagnose"],
      tags: ["diagnose"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("diagnose_selection", "Program.DiagnoseSelection"),
    exposure: mcp({
      name: "solidworks_diagnose_selection",
      tier: "debug",
      description: "Diagnose selection.",
      descriptionSource: "derived",
      input: SCHEMAS["diagnose"],
      tags: ["diagnose"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: selectionContext,
  }),
  tool({
    implementation: worker("resolve_selection", "Program.ResolveSelection"),
    exposure: mcp({
      name: "solidworks_resolve_selection",
      tier: "extended",
      description: "Resolve selection.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["resolve"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: selectionContext,
  }),
  tool({
    implementation: worker("explain_error", "Program.ExplainError"),
    exposure: mcp({
      name: "solidworks_explain_error",
      tier: "extended",
      description: "Explain error.",
      descriptionSource: "derived",
      input: SCHEMAS["explainError"],
      tags: ["explain"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_mass_properties", "Program.GetMassProperties"),
    exposure: mcp({
      name: "solidworks_get_mass_properties",
      tier: "extended",
      description: "Get mass properties.",
      descriptionSource: "derived",
      input: SCHEMAS["componentName"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: bindSelection([{ targetArg: "component_name", source: "selectedComponentName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("get_material", "Program.GetMaterial"),
    exposure: mcp({
      name: "solidworks_get_material",
      tier: "extended",
      description: "Return the material assigned to a part or component.",
      descriptionSource: "authored",
      input: SCHEMAS["optionalPath"],
      tags: ["get"],
      domains: ["assembly", "mate"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_bodies", "Program.ListBodies"),
    exposure: mcp({
      name: "solidworks_list_bodies",
      tier: "extended",
      description: "List bodies.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_equations", "Program.GetEquations"),
    exposure: mcp({
      name: "solidworks_get_equations",
      tier: "extended",
      description: "Get equations.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_sketches", "Program.ListSketches"),
    exposure: mcp({
      name: "solidworks_list_sketches",
      tier: "extended",
      description: "List sketches.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_selection", "Program.GetSelection"),
    exposure: mcp({
      name: "solidworks_get_selection",
      tier: "extended",
      description: "Get selection.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: selectionContext,
  }),
  tool({
    implementation: worker("list_display_states", "Program.ListDisplayStates"),
    exposure: mcp({
      name: "solidworks_list_display_states",
      tier: "extended",
      description: "List display states.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_open_documents", "Program.GetOpenDocuments"),
    exposure: mcp({
      name: "solidworks_get_open_documents",
      tier: "extended",
      description: "Get open documents.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("measure_distance", "Program.MeasureDistance"),
    exposure: mcp({
      name: "solidworks_measure_distance",
      tier: "extended",
      description: "Measure distance.",
      descriptionSource: "derived",
      input: SCHEMAS["measureDistance"],
      tags: ["measure"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_component_references", "Program.GetComponentReferences"),
    exposure: mcp({
      name: "solidworks_get_component_references",
      tier: "extended",
      description: "Get component references.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_broken_references", "Program.ListBrokenReferences"),
    exposure: mcp({
      name: "solidworks_list_broken_references",
      tier: "extended",
      description: "List broken references.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("new_document", "Program.NewDocument"),
    exposure: mcp({
      name: "solidworks_new_document",
      tier: "extended",
      description: "Create document.",
      descriptionSource: "derived",
      input: SCHEMAS["newDocument"],
      tags: ["new"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: true, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("demo_build_part", "Program.DemoBuildPart"),
    exposure: mcp({
      name: "solidworks_demo_build_part",
      tier: "core",
      description:
        "Build the deterministic demo part: 40 mm cube with Ø18 mm through-cylinders on Front, Top, and Right (confirm: true). Prefer output_path under the clone's .demo/DemoCube.SLDPRT when allowed. CLI equivalent: npm run demo:build-part.",
      descriptionSource: "authored",
      input: SCHEMAS["demoBuildPart"],
      tags: ["demo", "part", "modeling"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("close_document", "Program.CloseDocument"),
    exposure: mcp({
      name: "solidworks_close_document",
      tier: "extended",
      description: "Close document.",
      descriptionSource: "derived",
      input: SCHEMAS["closeDocument"],
      tags: ["close"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("activate_document", "Program.ActivateDocument"),
    exposure: mcp({
      name: "solidworks_activate_document",
      tier: "extended",
      description: "Activate document.",
      descriptionSource: "derived",
      input: SCHEMAS["open"],
      tags: ["activate"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("create_sketch", "Program.CreateSketch"),
    exposure: mcp({
      name: "solidworks_create_sketch",
      tier: "extended",
      description: "Create sketch.",
      descriptionSource: "derived",
      input: SCHEMAS["createSketch"],
      tags: ["create"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: bindSelection([{ targetArg: "plane_name", source: "selectedPlaneName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("sketch_rectangle", "Program.SketchRectangle"),
    exposure: mcp({
      name: "solidworks_sketch_rectangle",
      tier: "extended",
      description: "Create rectangle.",
      descriptionSource: "derived",
      input: SCHEMAS["sketchRectangle"],
      tags: ["sketch"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_extrude_boss", "Program.FeatureExtrudeBoss"),
    exposure: mcp({
      name: "solidworks_feature_extrude_boss",
      tier: "extended",
      description:
        "Extrude the active or named sketch as a boss. Use merge:false for a separate tool body. merge_body_name merges into one solid without auto-selecting unrelated multi-body solids. use_feat_scope/use_auto_select default from merge.",
      descriptionSource: "authored",
      input: SCHEMAS["featureExtrudeBoss"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("delete_feature", "Program.DeleteFeature"),
    exposure: mcp({
      name: "solidworks_delete_feature",
      tier: "extended",
      description: "Delete feature.",
      descriptionSource: "derived",
      input: SCHEMAS["deleteFeature"],
      tags: ["delete"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("dissolve_component", "Program.DissolveComponent"),
    exposure: mcp({
      name: "solidworks_dissolve_component",
      tier: "extended",
      description: "Dissolve component.",
      descriptionSource: "derived",
      input: SCHEMAS["dissolveComponent"],
      tags: ["dissolve"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("mirror_component", "Program.MirrorComponent"),
    exposure: mcp({
      name: "solidworks_mirror_component",
      tier: "extended",
      description: "Mirror component.",
      descriptionSource: "derived",
      input: SCHEMAS["mirrorComponent"],
      tags: ["mirror"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("pack_and_go", "Program.PackAndGo"),
    exposure: mcp({
      name: "solidworks_pack_and_go",
      tier: "extended",
      description: "Pack and go.",
      descriptionSource: "derived",
      input: SCHEMAS["packAndGo"],
      tags: ["pack"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("sketch_line", "Program.SketchLine"),
    exposure: mcp({
      name: "solidworks_sketch_line",
      tier: "extended",
      description: "Create line.",
      descriptionSource: "derived",
      input: SCHEMAS["sketchLine"],
      tags: ["sketch"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("sketch_circle", "Program.SketchCircle"),
    exposure: mcp({
      name: "solidworks_sketch_circle",
      tier: "extended",
      description: "Create circle.",
      descriptionSource: "derived",
      input: SCHEMAS["sketchCircle"],
      tags: ["sketch"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_sketch_circle_diameter", "Program.SetSketchCircleDiameter"),
    exposure: mcp({
      name: "solidworks_set_sketch_circle_diameter",
      tier: "extended",
      description: "Set a sketch circle diameter or adjust it by a delta.",
      descriptionSource: "authored",
      input: SCHEMAS["setSketchCircleDiameter"],
      tags: ["set", "sketch"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: bindSelection([{ targetArg: "sketch_name", source: "selectedFeatureName", selectionIndex: 1 }]),
  }),
  tool({
    implementation: worker("sketch_exit", "Program.SketchExit"),
    exposure: mcp({
      name: "solidworks_sketch_exit",
      tier: "extended",
      description: "Create exit.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["sketch"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_extrude_cut", "Program.FeatureExtrudeCut"),
    exposure: mcp({
      name: "solidworks_feature_extrude_cut",
      tier: "extended",
      description: "Manage extrude cut.",
      descriptionSource: "derived",
      input: SCHEMAS["featureExtrudeCut"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("combine_bodies", "Program.CombineBodies"),
    exposure: mcp({
      name: "solidworks_combine_bodies",
      tier: "extended",
      description:
        "Combine solid bodies (common/add/subtract). Common supports exactly two bodies and may be synthesized through subtract when InsertCombineFeature cannot create it. body_names[0] is the target/main body for subtract and common. With use_selection, highlight two bodies for dual selection via body_name (index 1) and tool_body_name (index 2). keep_body_names are copied and never consumed as synthesis subtract mains. Prefer body_names over feature_names for early features (Loft/Shell): Feature.GetFaces can mis-attribute ownership in multi-body parts.",
      descriptionSource: "authored",
      input: SCHEMAS["combineBodies"],
      tags: ["feature", "body", "boolean"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: bindSelection([
      { targetArg: "body_name", source: "selectedBodyName", selectionIndex: 1 },
      { targetArg: "tool_body_name", source: "selectedBodyName", selectionIndex: 2 },
    ]),
  }),
  tool({
    implementation: worker("round_side_arms_from_circle", "Program.RoundSideArmsFromCircle"),
    exposure: mcp({
      name: "solidworks_round_side_arms_from_circle",
      tier: "extended",
      description: "Round side arms from circle.",
      descriptionSource: "derived",
      input: SCHEMAS["roundSideArmsFromCircle"],
      tags: ["round"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_fillet", "Program.FeatureFillet"),
    exposure: mcp({
      name: "solidworks_feature_fillet",
      tier: "extended",
      description: "Manage fillet.",
      descriptionSource: "derived",
      input: SCHEMAS["featureFillet"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_chamfer", "Program.FeatureChamfer"),
    exposure: mcp({
      name: "solidworks_feature_chamfer",
      tier: "extended",
      description: "Manage chamfer.",
      descriptionSource: "derived",
      input: SCHEMAS["featureChamfer"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_mirror", "Program.FeatureMirror"),
    exposure: mcp({
      name: "solidworks_feature_mirror",
      tier: "extended",
      description: "Manage mirror.",
      descriptionSource: "derived",
      input: SCHEMAS["featureMirror"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_linear_pattern", "Program.FeatureLinearPattern"),
    exposure: mcp({
      name: "solidworks_feature_linear_pattern",
      tier: "extended",
      description: "Manage linear pattern.",
      descriptionSource: "derived",
      input: SCHEMAS["featureLinearPattern"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("feature_circular_pattern", "Program.FeatureCircularPattern"),
    exposure: mcp({
      name: "solidworks_feature_circular_pattern",
      tier: "extended",
      description: "Manage circular pattern.",
      descriptionSource: "derived",
      input: SCHEMAS["featureCircularPattern"],
      tags: ["feature"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_material", "Program.SetMaterial"),
    exposure: mcp({
      name: "solidworks_set_material",
      tier: "extended",
      description: "Assign a material to a part or component.",
      descriptionSource: "authored",
      input: SCHEMAS["setMaterial"],
      tags: ["set"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("set_mass_override", "Program.SetMassOverride"),
    exposure: mcp({
      name: "solidworks_set_mass_override",
      tier: "extended",
      description: "Set the assigned mass override on a part document in kilograms.",
      descriptionSource: "authored",
      input: SCHEMAS["setMassOverride"],
      tags: ["set", "mass"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("create_subassembly", "Program.CreateSubassembly"),
    exposure: mcp({
      name: "solidworks_create_subassembly",
      tier: "extended",
      description: "Create subassembly.",
      descriptionSource: "derived",
      input: SCHEMAS["createSubassembly"],
      tags: ["create"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("explode_view", "Program.ExplodeView"),
    exposure: mcp({
      name: "solidworks_explode_view",
      tier: "extended",
      description: "Explode view.",
      descriptionSource: "derived",
      input: SCHEMAS["explodeView"],
      tags: ["explode"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("copy_with_mates", "Program.CopyWithMates"),
    exposure: mcp({
      name: "solidworks_copy_with_mates",
      tier: "extended",
      description: "Copy with mates.",
      descriptionSource: "derived",
      input: SCHEMAS["copyWithMates"],
      tags: ["copy"],
      domains: ["assembly", "mate"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("create_drawing_from_model", "Program.CreateDrawingFromModel"),
    exposure: mcp({
      name: "solidworks_create_drawing_from_model",
      tier: "extended",
      description: "Create drawing from model.",
      descriptionSource: "derived",
      input: SCHEMAS["createDrawingFromModel"],
      tags: ["create"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: true }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("add_standard_views", "Program.AddStandardViews"),
    exposure: mcp({
      name: "solidworks_add_standard_views",
      tier: "extended",
      description: "Add standard views.",
      descriptionSource: "derived",
      input: SCHEMAS["addStandardViews"],
      tags: ["add"],
      domains: ["document"],
    }),
    safety: modelMutation({ destructive: false }),
    selection: noSelection,
  }),
  tool({
    implementation: worker("list_sheet_views", "Program.ListSheetViews"),
    exposure: mcp({
      name: "solidworks_list_sheet_views",
      tier: "extended",
      description: "List sheet views.",
      descriptionSource: "derived",
      input: SCHEMAS["optionalPath"],
      tags: ["list"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("import_step", "Program.ImportStep"),
    exposure: mcp({
      name: "solidworks_import_step",
      tier: "extended",
      description: "Import step.",
      descriptionSource: "derived",
      input: SCHEMAS["importStep"],
      tags: ["import"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("get_assembly_degrees_of_freedom", "Program.GetAssemblyDegreesOfFreedom"),
    exposure: mcp({
      name: "solidworks_get_assembly_degrees_of_freedom",
      tier: "extended",
      description: "Get assembly degrees of freedom.",
      descriptionSource: "derived",
      input: SCHEMAS["getAssemblyDegreesOfFreedom"],
      tags: ["get"],
      domains: ["document"],
    }),
    safety: readSafety(),
    selection: noSelection,
  }),
  tool({
    implementation: worker("export_link_transforms", "Program.ExportLinkTransforms"),
    exposure: mcp({
      name: "solidworks_export_link_transforms",
      tier: "extended",
      description: "Export link transforms.",
      descriptionSource: "derived",
      input: SCHEMAS["exportLinkTransforms"],
      tags: ["export"],
      domains: ["document"],
    }),
    safety: nonModelSideEffect({ destructive: false, rationale: "The current worker safety policy does not auto-checkpoint this command." }),
    selection: noSelection,
  }),
] as const satisfies readonly ToolSpec[];

